io:
  data_file: "census.csv"           
  model_dir: "model"                     
  model_subdir: null                      
  allow_overwrite: true                   
  file_name_suffixes:
    model: "_model.pkl"
    encoder: "_encoder.pkl"
    label_binarizer: "_label_binarizer.pkl"
    parameters: "_parameters.json"
    metrics: "_metrics.json"

train:
  target: "salary"
  holdout_size: 0.1
  test_size: 0.20
  random_state: 42
  min_threshold: 0.85 
  scoring: accuracy
  cv_folds: 5

  categorical_features:
    - workclass
    - education
    - marital-status
    - occupation
    - relationship
    - race
    - sex
    - native-country

  # Optional hyperparam search
  search: null
