_base: "_base.yaml" # ../base.yaml change to this if i decided to subfolder each config file to it's own model subfolder

io:               
  model_subdir: "decision_tree" 

model:
  class_path: "sklearn.tree.DecisionTreeClassifier"
  params:
    criterion: "gini"
    splitter: "best"
    max_depth: null
    min_samples_split: 2
    min_samples_leaf: 1
    min_weight_fraction_leaf: 0.0
    max_features: null
    # random_state: null
    max_leaf_nodes: null
    min_impurity_decrease: 0.0
    class_weight: null
    ccp_alpha: 0.0
