_base: "configs/base.yaml"

model:
  class_path: "sklearn.neighbors.KNeighborsClassifier"
  params:
    n_neighbors: 5
    weights: "uniform"
    algorithm: "auto"
    leaf_size: 30
    p: 2
    metric: "minkowski"
    metric_params: null
    # n_jobs: null
