_base: "configs/base.yaml"

model:
  class_path: "sklearn.linear_model.LogisticRegression"
  params:
    penalty: "l2"
    dual: false
    tol: 0.0001
    C: 1.0
    fit_intercept: true
    intercept_scaling: 1
    # class_weight: null
    # random_state: null
    solver: "lbfgs"
    max_iter: 100
    # multi_class: "auto"
    verbose: 0
    warm_start: false
    # n_jobs: null
    l1_ratio: null
